### ISSUE TITLE
Error when hitting enemies with certain projectiles

### ISSUE THREAD

**Issue by Tepig125** [PvtFudgepants/Tmodloader-ColoredDamageTypes#2]
For some reason, when I use certain weapons from my modded class against enemies, it gives me an error saying "Object reference not set to an instance of an object". The projectiles that trigger this error disappear immediately on contact with enemies (they don't even die, just disappear)
Based on my testing, this happens exclusively with projectiles that are not the Item.Shoot of the weapon. For example, if one weapon has three unique projectiles it fires, only the "main" projectile (whichever one is set using Item.Shoot) will be able to deal damage and will not cause issues
Here is the client.log file from the session where I was messing around with this: [client.log](https://github.com/PvtFudgepants/Tmodloader-ColoredDamageTypes/files/8636843/client.log)

Edit: I double-checked with some vanilla class weapons from my mod that have multiple projectile types, and they all seem to behave as normal. As far as I'm aware, this bug seems to only happen with my mod's class (or maybe all modded classes, but I haven't done enough testing to know for sure)

**Comment by PvtFudgepants** [comment]
Just released an update and it should work now.
I had forgotten to set it to check the projectile's type for custom projectiles, instead of the item damage type.
It was also prioritizing the item.shoot property over the *actual* projectile type, which I now fixed.

Before if you had a melee sword that shot magic projectiles, the projectile would always show up as melee even if it was actually counting as magic.

After the new update the projectile will properly count as the type that the projectile is set to.

Thanks for testing it though. and be sure to let me know if any other issues come up!
